package com.example.student.dto.ai;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;
import java.util.Map;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Schema(description = "Response containing aggregated stats and AI-generated narrative insights")
public class AnalyticsResponseDto {

    @Schema(description = "Raw metrics retrieved from the database")
    private RawStatsDto rawStats;

    @Schema(description = "Narrative analytical insights generated by Claude AI", example = "Based on the data, Computer Science dominates enrollment at 34%...")
    private String aiInsights;

    @Schema(description = "Timestamp when report was generated", example = "2026-06-07T10:00:00")
    private LocalDateTime generatedAt;

    @Schema(description = "Flag indicating if the response was served from cache", example = "true")
    private boolean cachedResponse;

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    @Schema(description = "Structured statistical metrics")
    public static class RawStatsDto {
        @Schema(description = "Total number of student records in database", example = "100")
        private long totalStudents;

        @Schema(description = "Distribution of students per course name")
        private Map<String, Long> courseDistribution;

        @Schema(description = "Average age of students", example = "21.3")
        private double averageAge;

        @Schema(description = "Enrollment trends over the past months (month -> count)")
        private Map<String, Long> enrollmentTrend;

        @Schema(description = "Distribution of students inside age buckets (e.g. 18-20, 21-23, 24+)")
        private Map<String, Long> ageRangeDistribution;
    }
}
